=== tmatsuno/ssdb/SSDB/etc/xsd/SecretStringDBXMLSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns="SecretStringDB"
            attributeFormDefault="unqualified"
            elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="SecretStringDB">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Entry" maxOccurs="unbounded" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="String" maxOccurs="unbounded" minOccurs="0">
                <xsd:complexType>
                  <xsd:attribute name="data" type="xsd:string" use="required" />
                  <xsd:attribute name="create" type="xsd:dateTime" use="required" />
                  <xsd:attribute name="expire" type="xsd:dateTime" use="required" />
                  <xsd:attribute name="status" type="xsd:boolean" use="required" />
                  <xsd:attribute name="id" type="xsd:integer" use="required" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== tmatsuno/ssdb/SSDB/etc/samplexml/ssdbsample5.xml
<?xml version="1.0" encoding="UTF-8"?>
<SecretStringDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/SecretStringDBXMLSchema.xsd">
    <Entry name="sample1">
        <String status="false" expire="2023-06-25T00:00:00+09:00"
            create="2013-06-25T00:00:00+09:00" data="1samplestringdatafalse" id="1" />
        <String status="true" expire="2023-06-25T00:00:00+09:00"
            create="2013-06-25T00:00:00+09:00" data="2samplestringdatatrue" id="2" />
        <String status="false" expire="2023-06-25T00:00:00+09:00"
            create="2013-06-25T00:00:00+09:00" data="3samplestringdatafalse" id="3" />
    </Entry>
    <Entry name="sample2">
        <String status="false" expire="2023-06-25T00:00:00+09:00"
            create="2013-06-25T00:00:00+09:00" data="4samplestringdatafalse" id="1" />
        <String status="true" expire="2023-06-25T00:00:00+09:00"
            create="2013-06-25T00:00:00+09:00" data="5samplestringdatatrue" id="2" />
    </Entry>
</SecretStringDB>
